import React from "react";
import {
  ExternalLink,
  Settings,
  LogOut,
  KeyRound,
  ShieldCheck,
  Trash2,
  LifeBuoy,
  Sparkles,
  Bell,
  UserRound,
  ClipboardCheck,
  MessageSquare,
  ShoppingBag,
  ArrowRight,
  ChevronLeft,
  X,
  TriangleAlert,
  Phone,
  Send,
  Check,
  Mic,
  Eye,
  EyeOff,
} from "lucide-react";

const icons = {
  external: ExternalLink,
  settings: Settings,
  logout: LogOut,
  key: KeyRound,
  shield: ShieldCheck,
  trash: Trash2,
  support: LifeBuoy,
  spark: Sparkles,
  bell: Bell,
  user: UserRound,
  clipboard: ClipboardCheck,
  message: MessageSquare,
  bag: ShoppingBag,
  arrow: ArrowRight,
  back: ChevronLeft,
  close: X,
  warning: TriangleAlert,
  phone: Phone,
  send: Send,
  check: Check,
  mic: Mic,
  eye: Eye,
  eyeOff: EyeOff,
};
export default function Icon({ name, size = 22 }) {
  const Component = icons[name] || Sparkles;
  return <Component size={size} strokeWidth={1.8} aria-hidden="true" />;
}
