// Prefijos telefónicos internacionales (lista completa). Selector del checkout.
export const PREFIJO_DEFECTO = '+34';

export const PREFIJOS = [
  { codigo: '+93', pais: 'Afganistán' }, { codigo: '+355', pais: 'Albania' }, { codigo: '+49', pais: 'Alemania' },
  { codigo: '+376', pais: 'Andorra' }, { codigo: '+244', pais: 'Angola' }, { codigo: '+1268', pais: 'Antigua y Barbuda' },
  { codigo: '+966', pais: 'Arabia Saudí' }, { codigo: '+213', pais: 'Argelia' }, { codigo: '+54', pais: 'Argentina' },
  { codigo: '+374', pais: 'Armenia' }, { codigo: '+61', pais: 'Australia' }, { codigo: '+43', pais: 'Austria' },
  { codigo: '+994', pais: 'Azerbaiyán' }, { codigo: '+1242', pais: 'Bahamas' }, { codigo: '+973', pais: 'Baréin' },
  { codigo: '+880', pais: 'Bangladés' }, { codigo: '+1246', pais: 'Barbados' }, { codigo: '+32', pais: 'Bélgica' },
  { codigo: '+501', pais: 'Belice' }, { codigo: '+229', pais: 'Benín' }, { codigo: '+975', pais: 'Bután' },
  { codigo: '+375', pais: 'Bielorrusia' }, { codigo: '+591', pais: 'Bolivia' }, { codigo: '+387', pais: 'Bosnia y Herzegovina' },
  { codigo: '+267', pais: 'Botsuana' }, { codigo: '+55', pais: 'Brasil' }, { codigo: '+673', pais: 'Brunéi' },
  { codigo: '+359', pais: 'Bulgaria' }, { codigo: '+226', pais: 'Burkina Faso' }, { codigo: '+257', pais: 'Burundi' },
  { codigo: '+238', pais: 'Cabo Verde' }, { codigo: '+855', pais: 'Camboya' }, { codigo: '+237', pais: 'Camerún' },
  { codigo: '+1', pais: 'Canadá' }, { codigo: '+974', pais: 'Catar' }, { codigo: '+235', pais: 'Chad' },
  { codigo: '+56', pais: 'Chile' }, { codigo: '+86', pais: 'China' }, { codigo: '+357', pais: 'Chipre' },
  { codigo: '+57', pais: 'Colombia' }, { codigo: '+269', pais: 'Comoras' }, { codigo: '+242', pais: 'Congo' },
  { codigo: '+243', pais: 'Congo (RD)' }, { codigo: '+82', pais: 'Corea del Sur' }, { codigo: '+225', pais: 'Costa de Marfil' },
  { codigo: '+506', pais: 'Costa Rica' }, { codigo: '+385', pais: 'Croacia' }, { codigo: '+53', pais: 'Cuba' },
  { codigo: '+45', pais: 'Dinamarca' }, { codigo: '+1767', pais: 'Dominica' }, { codigo: '+593', pais: 'Ecuador' },
  { codigo: '+20', pais: 'Egipto' }, { codigo: '+503', pais: 'El Salvador' }, { codigo: '+971', pais: 'Emiratos Árabes Unidos' },
  { codigo: '+291', pais: 'Eritrea' }, { codigo: '+421', pais: 'Eslovaquia' }, { codigo: '+386', pais: 'Eslovenia' },
  { codigo: '+34', pais: 'España' }, { codigo: '+1', pais: 'Estados Unidos' }, { codigo: '+372', pais: 'Estonia' },
  { codigo: '+251', pais: 'Etiopía' }, { codigo: '+63', pais: 'Filipinas' }, { codigo: '+358', pais: 'Finlandia' },
  { codigo: '+679', pais: 'Fiyi' }, { codigo: '+33', pais: 'Francia' }, { codigo: '+241', pais: 'Gabón' },
  { codigo: '+220', pais: 'Gambia' }, { codigo: '+995', pais: 'Georgia' }, { codigo: '+233', pais: 'Ghana' },
  { codigo: '+1473', pais: 'Granada' }, { codigo: '+30', pais: 'Grecia' }, { codigo: '+502', pais: 'Guatemala' },
  { codigo: '+224', pais: 'Guinea' }, { codigo: '+245', pais: 'Guinea-Bisáu' }, { codigo: '+240', pais: 'Guinea Ecuatorial' },
  { codigo: '+592', pais: 'Guyana' }, { codigo: '+509', pais: 'Haití' }, { codigo: '+504', pais: 'Honduras' },
  { codigo: '+36', pais: 'Hungría' }, { codigo: '+91', pais: 'India' }, { codigo: '+62', pais: 'Indonesia' },
  { codigo: '+964', pais: 'Irak' }, { codigo: '+98', pais: 'Irán' }, { codigo: '+353', pais: 'Irlanda' },
  { codigo: '+354', pais: 'Islandia' }, { codigo: '+972', pais: 'Israel' }, { codigo: '+39', pais: 'Italia' },
  { codigo: '+1876', pais: 'Jamaica' }, { codigo: '+81', pais: 'Japón' }, { codigo: '+962', pais: 'Jordania' },
  { codigo: '+7', pais: 'Kazajistán' }, { codigo: '+254', pais: 'Kenia' }, { codigo: '+996', pais: 'Kirguistán' },
  { codigo: '+686', pais: 'Kiribati' }, { codigo: '+965', pais: 'Kuwait' }, { codigo: '+856', pais: 'Laos' },
  { codigo: '+266', pais: 'Lesoto' }, { codigo: '+371', pais: 'Letonia' }, { codigo: '+961', pais: 'Líbano' },
  { codigo: '+231', pais: 'Liberia' }, { codigo: '+218', pais: 'Libia' }, { codigo: '+423', pais: 'Liechtenstein' },
  { codigo: '+370', pais: 'Lituania' }, { codigo: '+352', pais: 'Luxemburgo' }, { codigo: '+389', pais: 'Macedonia del Norte' },
  { codigo: '+261', pais: 'Madagascar' }, { codigo: '+60', pais: 'Malasia' }, { codigo: '+265', pais: 'Malaui' },
  { codigo: '+960', pais: 'Maldivas' }, { codigo: '+223', pais: 'Malí' }, { codigo: '+356', pais: 'Malta' },
  { codigo: '+212', pais: 'Marruecos' }, { codigo: '+230', pais: 'Mauricio' }, { codigo: '+222', pais: 'Mauritania' },
  { codigo: '+52', pais: 'México' }, { codigo: '+691', pais: 'Micronesia' }, { codigo: '+373', pais: 'Moldavia' },
  { codigo: '+377', pais: 'Mónaco' }, { codigo: '+976', pais: 'Mongolia' }, { codigo: '+382', pais: 'Montenegro' },
  { codigo: '+258', pais: 'Mozambique' }, { codigo: '+95', pais: 'Myanmar' }, { codigo: '+264', pais: 'Namibia' },
  { codigo: '+977', pais: 'Nepal' }, { codigo: '+505', pais: 'Nicaragua' }, { codigo: '+227', pais: 'Níger' },
  { codigo: '+234', pais: 'Nigeria' }, { codigo: '+47', pais: 'Noruega' }, { codigo: '+64', pais: 'Nueva Zelanda' },
  { codigo: '+968', pais: 'Omán' }, { codigo: '+31', pais: 'Países Bajos' }, { codigo: '+92', pais: 'Pakistán' },
  { codigo: '+680', pais: 'Palaos' }, { codigo: '+507', pais: 'Panamá' }, { codigo: '+675', pais: 'Papúa Nueva Guinea' },
  { codigo: '+595', pais: 'Paraguay' }, { codigo: '+51', pais: 'Perú' }, { codigo: '+48', pais: 'Polonia' },
  { codigo: '+351', pais: 'Portugal' }, { codigo: '+44', pais: 'Reino Unido' }, { codigo: '+236', pais: 'Rep. Centroafricana' },
  { codigo: '+420', pais: 'República Checa' }, { codigo: '+1809', pais: 'República Dominicana' }, { codigo: '+250', pais: 'Ruanda' },
  { codigo: '+40', pais: 'Rumanía' }, { codigo: '+7', pais: 'Rusia' }, { codigo: '+685', pais: 'Samoa' },
  { codigo: '+1869', pais: 'San Cristóbal y Nieves' }, { codigo: '+378', pais: 'San Marino' }, { codigo: '+1758', pais: 'Santa Lucía' },
  { codigo: '+239', pais: 'Santo Tomé y Príncipe' }, { codigo: '+1784', pais: 'San Vicente y las Granadinas' }, { codigo: '+221', pais: 'Senegal' },
  { codigo: '+381', pais: 'Serbia' }, { codigo: '+248', pais: 'Seychelles' }, { codigo: '+232', pais: 'Sierra Leona' },
  { codigo: '+65', pais: 'Singapur' }, { codigo: '+963', pais: 'Siria' }, { codigo: '+252', pais: 'Somalia' },
  { codigo: '+94', pais: 'Sri Lanka' }, { codigo: '+27', pais: 'Sudáfrica' }, { codigo: '+249', pais: 'Sudán' },
  { codigo: '+211', pais: 'Sudán del Sur' }, { codigo: '+46', pais: 'Suecia' }, { codigo: '+41', pais: 'Suiza' },
  { codigo: '+597', pais: 'Surinam' }, { codigo: '+66', pais: 'Tailandia' }, { codigo: '+255', pais: 'Tanzania' },
  { codigo: '+992', pais: 'Tayikistán' }, { codigo: '+670', pais: 'Timor Oriental' }, { codigo: '+228', pais: 'Togo' },
  { codigo: '+676', pais: 'Tonga' }, { codigo: '+1868', pais: 'Trinidad y Tobago' }, { codigo: '+216', pais: 'Túnez' },
  { codigo: '+993', pais: 'Turkmenistán' }, { codigo: '+90', pais: 'Turquía' }, { codigo: '+688', pais: 'Tuvalu' },
  { codigo: '+380', pais: 'Ucrania' }, { codigo: '+256', pais: 'Uganda' }, { codigo: '+598', pais: 'Uruguay' },
  { codigo: '+998', pais: 'Uzbekistán' }, { codigo: '+678', pais: 'Vanuatu' }, { codigo: '+58', pais: 'Venezuela' },
  { codigo: '+84', pais: 'Vietnam' }, { codigo: '+967', pais: 'Yemen' }, { codigo: '+253', pais: 'Yibuti' },
  { codigo: '+260', pais: 'Zambia' }, { codigo: '+263', pais: 'Zimbabue' },
];
