// Prefijos telefónicos internacionales (lista completa). Selector del checkout.
export const PREFIJO_DEFECTO = '+34';

export const PREFIJOS = [
  { bandera: '🇦🇫', codigo: '+93', pais: 'Afganistán' }, { bandera: '🇦🇱', codigo: '+355', pais: 'Albania' }, { bandera: '🇩🇪', codigo: '+49', pais: 'Alemania' },
  { bandera: '🇦🇩', codigo: '+376', pais: 'Andorra' }, { bandera: '🇦🇴', codigo: '+244', pais: 'Angola' }, { bandera: '🇦🇬', codigo: '+1268', pais: 'Antigua y Barbuda' },
  { bandera: '🇸🇦', codigo: '+966', pais: 'Arabia Saudí' }, { bandera: '🇩🇿', codigo: '+213', pais: 'Argelia' }, { bandera: '🇦🇷', codigo: '+54', pais: 'Argentina' },
  { bandera: '🇦🇲', codigo: '+374', pais: 'Armenia' }, { bandera: '🇦🇺', codigo: '+61', pais: 'Australia' }, { bandera: '🇦🇹', codigo: '+43', pais: 'Austria' },
  { bandera: '🇦🇿', codigo: '+994', pais: 'Azerbaiyán' }, { bandera: '🇧🇸', codigo: '+1242', pais: 'Bahamas' }, { bandera: '🇧🇭', codigo: '+973', pais: 'Baréin' },
  { bandera: '🇧🇩', codigo: '+880', pais: 'Bangladés' }, { bandera: '🇧🇧', codigo: '+1246', pais: 'Barbados' }, { bandera: '🇧🇪', codigo: '+32', pais: 'Bélgica' },
  { bandera: '🇧🇿', codigo: '+501', pais: 'Belice' }, { bandera: '🇧🇯', codigo: '+229', pais: 'Benín' }, { bandera: '🇧🇹', codigo: '+975', pais: 'Bután' },
  { bandera: '🇧🇾', codigo: '+375', pais: 'Bielorrusia' }, { bandera: '🇧🇴', codigo: '+591', pais: 'Bolivia' }, { bandera: '🇧🇦', codigo: '+387', pais: 'Bosnia y Herzegovina' },
  { bandera: '🇧🇼', codigo: '+267', pais: 'Botsuana' }, { bandera: '🇧🇷', codigo: '+55', pais: 'Brasil' }, { bandera: '🇧🇳', codigo: '+673', pais: 'Brunéi' },
  { bandera: '🇧🇬', codigo: '+359', pais: 'Bulgaria' }, { bandera: '🇧🇫', codigo: '+226', pais: 'Burkina Faso' }, { bandera: '🇧🇮', codigo: '+257', pais: 'Burundi' },
  { bandera: '🇨🇻', codigo: '+238', pais: 'Cabo Verde' }, { bandera: '🇰🇭', codigo: '+855', pais: 'Camboya' }, { bandera: '🇨🇲', codigo: '+237', pais: 'Camerún' },
  { bandera: '🇨🇦', codigo: '+1', pais: 'Canadá' }, { bandera: '🇶🇦', codigo: '+974', pais: 'Catar' }, { bandera: '🇹🇩', codigo: '+235', pais: 'Chad' },
  { bandera: '🇨🇱', codigo: '+56', pais: 'Chile' }, { bandera: '🇨🇳', codigo: '+86', pais: 'China' }, { bandera: '🇨🇾', codigo: '+357', pais: 'Chipre' },
  { bandera: '🇨🇴', codigo: '+57', pais: 'Colombia' }, { bandera: '🇰🇲', codigo: '+269', pais: 'Comoras' }, { bandera: '🇨🇬', codigo: '+242', pais: 'Congo' },
  { bandera: '🇨🇩', codigo: '+243', pais: 'Congo (RD)' }, { bandera: '🇰🇷', codigo: '+82', pais: 'Corea del Sur' }, { bandera: '🇨🇮', codigo: '+225', pais: 'Costa de Marfil' },
  { bandera: '🇨🇷', codigo: '+506', pais: 'Costa Rica' }, { bandera: '🇭🇷', codigo: '+385', pais: 'Croacia' }, { bandera: '🇨🇺', codigo: '+53', pais: 'Cuba' },
  { bandera: '🇩🇰', codigo: '+45', pais: 'Dinamarca' }, { bandera: '🇩🇲', codigo: '+1767', pais: 'Dominica' }, { bandera: '🇪🇨', codigo: '+593', pais: 'Ecuador' },
  { bandera: '🇪🇬', codigo: '+20', pais: 'Egipto' }, { bandera: '🇸🇻', codigo: '+503', pais: 'El Salvador' }, { bandera: '🇦🇪', codigo: '+971', pais: 'Emiratos Árabes Unidos' },
  { bandera: '🇪🇷', codigo: '+291', pais: 'Eritrea' }, { bandera: '🇸🇰', codigo: '+421', pais: 'Eslovaquia' }, { bandera: '🇸🇮', codigo: '+386', pais: 'Eslovenia' },
  { bandera: '🇪🇸', codigo: '+34', pais: 'España' }, { bandera: '🇺🇸', codigo: '+1', pais: 'Estados Unidos' }, { bandera: '🇪🇪', codigo: '+372', pais: 'Estonia' },
  { bandera: '🇪🇹', codigo: '+251', pais: 'Etiopía' }, { bandera: '🇵🇭', codigo: '+63', pais: 'Filipinas' }, { bandera: '🇫🇮', codigo: '+358', pais: 'Finlandia' },
  { bandera: '🇫🇯', codigo: '+679', pais: 'Fiyi' }, { bandera: '🇫🇷', codigo: '+33', pais: 'Francia' }, { bandera: '🇬🇦', codigo: '+241', pais: 'Gabón' },
  { bandera: '🇬🇲', codigo: '+220', pais: 'Gambia' }, { bandera: '🇬🇪', codigo: '+995', pais: 'Georgia' }, { bandera: '🇬🇭', codigo: '+233', pais: 'Ghana' },
  { bandera: '🇬🇩', codigo: '+1473', pais: 'Granada' }, { bandera: '🇬🇷', codigo: '+30', pais: 'Grecia' }, { bandera: '🇬🇹', codigo: '+502', pais: 'Guatemala' },
  { bandera: '🇬🇳', codigo: '+224', pais: 'Guinea' }, { bandera: '🇬🇼', codigo: '+245', pais: 'Guinea-Bisáu' }, { bandera: '🇬🇶', codigo: '+240', pais: 'Guinea Ecuatorial' },
  { bandera: '🇬🇾', codigo: '+592', pais: 'Guyana' }, { bandera: '🇭🇹', codigo: '+509', pais: 'Haití' }, { bandera: '🇭🇳', codigo: '+504', pais: 'Honduras' },
  { bandera: '🇭🇺', codigo: '+36', pais: 'Hungría' }, { bandera: '🇮🇳', codigo: '+91', pais: 'India' }, { bandera: '🇮🇩', codigo: '+62', pais: 'Indonesia' },
  { bandera: '🇮🇶', codigo: '+964', pais: 'Irak' }, { bandera: '🇮🇷', codigo: '+98', pais: 'Irán' }, { bandera: '🇮🇪', codigo: '+353', pais: 'Irlanda' },
  { bandera: '🇮🇸', codigo: '+354', pais: 'Islandia' }, { bandera: '🇮🇱', codigo: '+972', pais: 'Israel' }, { bandera: '🇮🇹', codigo: '+39', pais: 'Italia' },
  { bandera: '🇯🇲', codigo: '+1876', pais: 'Jamaica' }, { bandera: '🇯🇵', codigo: '+81', pais: 'Japón' }, { bandera: '🇯🇴', codigo: '+962', pais: 'Jordania' },
  { bandera: '🇰🇿', codigo: '+7', pais: 'Kazajistán' }, { bandera: '🇰🇪', codigo: '+254', pais: 'Kenia' }, { bandera: '🇰🇬', codigo: '+996', pais: 'Kirguistán' },
  { bandera: '🇰🇮', codigo: '+686', pais: 'Kiribati' }, { bandera: '🇰🇼', codigo: '+965', pais: 'Kuwait' }, { bandera: '🇱🇦', codigo: '+856', pais: 'Laos' },
  { bandera: '🇱🇸', codigo: '+266', pais: 'Lesoto' }, { bandera: '🇱🇻', codigo: '+371', pais: 'Letonia' }, { bandera: '🇱🇧', codigo: '+961', pais: 'Líbano' },
  { bandera: '🇱🇷', codigo: '+231', pais: 'Liberia' }, { bandera: '🇱🇾', codigo: '+218', pais: 'Libia' }, { bandera: '🇱🇮', codigo: '+423', pais: 'Liechtenstein' },
  { bandera: '🇱🇹', codigo: '+370', pais: 'Lituania' }, { bandera: '🇱🇺', codigo: '+352', pais: 'Luxemburgo' }, { bandera: '🇲🇰', codigo: '+389', pais: 'Macedonia del Norte' },
  { bandera: '🇲🇬', codigo: '+261', pais: 'Madagascar' }, { bandera: '🇲🇾', codigo: '+60', pais: 'Malasia' }, { bandera: '🇲🇼', codigo: '+265', pais: 'Malaui' },
  { bandera: '🇲🇻', codigo: '+960', pais: 'Maldivas' }, { bandera: '🇲🇱', codigo: '+223', pais: 'Malí' }, { bandera: '🇲🇹', codigo: '+356', pais: 'Malta' },
  { bandera: '🇲🇦', codigo: '+212', pais: 'Marruecos' }, { bandera: '🇲🇺', codigo: '+230', pais: 'Mauricio' }, { bandera: '🇲🇷', codigo: '+222', pais: 'Mauritania' },
  { bandera: '🇲🇽', codigo: '+52', pais: 'México' }, { bandera: '🇫🇲', codigo: '+691', pais: 'Micronesia' }, { bandera: '🇲🇩', codigo: '+373', pais: 'Moldavia' },
  { bandera: '🇲🇨', codigo: '+377', pais: 'Mónaco' }, { bandera: '🇲🇳', codigo: '+976', pais: 'Mongolia' }, { bandera: '🇲🇪', codigo: '+382', pais: 'Montenegro' },
  { bandera: '🇲🇿', codigo: '+258', pais: 'Mozambique' }, { bandera: '🇲🇲', codigo: '+95', pais: 'Myanmar' }, { bandera: '🇳🇦', codigo: '+264', pais: 'Namibia' },
  { bandera: '🇳🇵', codigo: '+977', pais: 'Nepal' }, { bandera: '🇳🇮', codigo: '+505', pais: 'Nicaragua' }, { bandera: '🇳🇪', codigo: '+227', pais: 'Níger' },
  { bandera: '🇳🇬', codigo: '+234', pais: 'Nigeria' }, { bandera: '🇳🇴', codigo: '+47', pais: 'Noruega' }, { bandera: '🇳🇿', codigo: '+64', pais: 'Nueva Zelanda' },
  { bandera: '🇴🇲', codigo: '+968', pais: 'Omán' }, { bandera: '🇳🇱', codigo: '+31', pais: 'Países Bajos' }, { bandera: '🇵🇰', codigo: '+92', pais: 'Pakistán' },
  { bandera: '🇵🇼', codigo: '+680', pais: 'Palaos' }, { bandera: '🇵🇦', codigo: '+507', pais: 'Panamá' }, { bandera: '🇵🇬', codigo: '+675', pais: 'Papúa Nueva Guinea' },
  { bandera: '🇵🇾', codigo: '+595', pais: 'Paraguay' }, { bandera: '🇵🇪', codigo: '+51', pais: 'Perú' }, { bandera: '🇵🇱', codigo: '+48', pais: 'Polonia' },
  { bandera: '🇵🇹', codigo: '+351', pais: 'Portugal' }, { bandera: '🇬🇧', codigo: '+44', pais: 'Reino Unido' }, { bandera: '🇨🇫', codigo: '+236', pais: 'Rep. Centroafricana' },
  { bandera: '🇨🇿', codigo: '+420', pais: 'República Checa' }, { bandera: '🇩🇴', codigo: '+1809', pais: 'República Dominicana' }, { bandera: '🇷🇼', codigo: '+250', pais: 'Ruanda' },
  { bandera: '🇷🇴', codigo: '+40', pais: 'Rumanía' }, { bandera: '🇷🇺', codigo: '+7', pais: 'Rusia' }, { bandera: '🇼🇸', codigo: '+685', pais: 'Samoa' },
  { bandera: '🇰🇳', codigo: '+1869', pais: 'San Cristóbal y Nieves' }, { bandera: '🇸🇲', codigo: '+378', pais: 'San Marino' }, { bandera: '🇱🇨', codigo: '+1758', pais: 'Santa Lucía' },
  { bandera: '🇸🇹', codigo: '+239', pais: 'Santo Tomé y Príncipe' }, { bandera: '🇻🇨', codigo: '+1784', pais: 'San Vicente y las Granadinas' }, { bandera: '🇸🇳', codigo: '+221', pais: 'Senegal' },
  { bandera: '🇷🇸', codigo: '+381', pais: 'Serbia' }, { bandera: '🇸🇨', codigo: '+248', pais: 'Seychelles' }, { bandera: '🇸🇱', codigo: '+232', pais: 'Sierra Leona' },
  { bandera: '🇸🇬', codigo: '+65', pais: 'Singapur' }, { bandera: '🇸🇾', codigo: '+963', pais: 'Siria' }, { bandera: '🇸🇴', codigo: '+252', pais: 'Somalia' },
  { bandera: '🇱🇰', codigo: '+94', pais: 'Sri Lanka' }, { bandera: '🇿🇦', codigo: '+27', pais: 'Sudáfrica' }, { bandera: '🇸🇩', codigo: '+249', pais: 'Sudán' },
  { bandera: '🇸🇸', codigo: '+211', pais: 'Sudán del Sur' }, { bandera: '🇸🇪', codigo: '+46', pais: 'Suecia' }, { bandera: '🇨🇭', codigo: '+41', pais: 'Suiza' },
  { bandera: '🇸🇷', codigo: '+597', pais: 'Surinam' }, { bandera: '🇹🇭', codigo: '+66', pais: 'Tailandia' }, { bandera: '🇹🇿', codigo: '+255', pais: 'Tanzania' },
  { bandera: '🇹🇯', codigo: '+992', pais: 'Tayikistán' }, { bandera: '🇹🇱', codigo: '+670', pais: 'Timor Oriental' }, { bandera: '🇹🇬', codigo: '+228', pais: 'Togo' },
  { bandera: '🇹🇴', codigo: '+676', pais: 'Tonga' }, { bandera: '🇹🇹', codigo: '+1868', pais: 'Trinidad y Tobago' }, { bandera: '🇹🇳', codigo: '+216', pais: 'Túnez' },
  { bandera: '🇹🇲', codigo: '+993', pais: 'Turkmenistán' }, { bandera: '🇹🇷', codigo: '+90', pais: 'Turquía' }, { bandera: '🇹🇻', codigo: '+688', pais: 'Tuvalu' },
  { bandera: '🇺🇦', codigo: '+380', pais: 'Ucrania' }, { bandera: '🇺🇬', codigo: '+256', pais: 'Uganda' }, { bandera: '🇺🇾', codigo: '+598', pais: 'Uruguay' },
  { bandera: '🇺🇿', codigo: '+998', pais: 'Uzbekistán' }, { bandera: '🇻🇺', codigo: '+678', pais: 'Vanuatu' }, { bandera: '🇻🇪', codigo: '+58', pais: 'Venezuela' },
  { bandera: '🇻🇳', codigo: '+84', pais: 'Vietnam' }, { bandera: '🇾🇪', codigo: '+967', pais: 'Yemen' }, { bandera: '🇩🇯', codigo: '+253', pais: 'Yibuti' },
  { bandera: '🇿🇲', codigo: '+260', pais: 'Zambia' }, { bandera: '🇿🇼', codigo: '+263', pais: 'Zimbabue' },
];
