// Sólo maquetas de revisión. No importa proveedores, autenticación, API ni estado del producto.
import React, {useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,Pencil,RefreshCw} from 'lucide-react';
import Icon from '../../../../frontend/app/src/Icon.jsx';
import '../../../../frontend/app/src/app.css';
import './pantallas.css';
const params=new URLSearchParams(location.search);
const aliases={nombre:'consulta',contacto:'preguntas',requisitos:'preguntas','registro-necesario':'datos-contacto'};
const raw=params.get('s')||'inicio';
const initial=aliases[raw]||raw;
const captura=params.has('captura');
const href = s => `./pantalla.html?s=${s}`;
function go(s){location.href=href(s)}
const memo=captura?{}:JSON.parse(sessionStorage.getItem('maqueta-lidia-datos') || '{}');
function App(){
 const [screen,setScreen]=useState(initial);
 const [nombre,setNombre]=useState(memo.nombre || 'Lucía Martín');
 const [chatOrigin,setChatOrigin]=useState(memo.chatOrigin || 'inicio');
 const [pais,setPais]=useState(memo.pais || 'Perú');
 const [countryAnswered,setCountryAnswered]=useState(false);
 const [legalOrigin,setLegalOrigin]=useState('registro');
 const [authOrigin,setAuthOrigin]=useState('recibido');
 const [protectedOrigin,setProtectedOrigin]=useState('inicio');
 const [contacto,setContacto]=useState(memo.contacto || '+34 600 000 000');
 const [email,setEmail]=useState(memo.email || 'lucia@example.com');
 const [localMessages,setLocalMessages]=useState([]);
 const [contactType,setContactType]=useState(memo.contacto?.includes('@')?'email':'tel');
 const [draft,setDraft]=useState('');
 const [visible,setVisible]=useState(false);
 const [renaming,setRenaming]=useState(false);
 const [title,setTitle]=useState('Canje de carnet');
 const [search,setSearch]=useState('');
 const [notice,setNotice]=useState('');
 const chatScreens=['consulta','preguntas','resultado','contactar','datos-contacto','retomado','recibido','revision','cancelado'];
 const isChat=chatScreens.includes(screen);
 const auth=['registro','acceso','verificar','vinculando','caducado','recuperacion','legal','instalar'].includes(screen);
 useEffect(()=>{sessionStorage.setItem('maqueta-lidia-datos',JSON.stringify({nombre,contacto,email,pais,chatOrigin}));},[nombre,contacto,email,pais,chatOrigin]);
 useEffect(()=>{if(['retomado','recibido'].includes(screen)){const m=document.getElementById('main');if(m)m.scrollTop=m.scrollHeight;}},[screen]);
 const persist=()=>sessionStorage.setItem('maqueta-lidia-datos',JSON.stringify({nombre,contacto,email,pais,chatOrigin}));
 const navigate=s=>{if(s==='restricciones'&&!['acceso','registro','restricciones'].includes(screen))setProtectedOrigin(screen);if(screen==='restricciones'&&s==='acceso')setAuthOrigin('restricciones');if(['recibido','cancelado'].includes(screen)&&['registro','acceso'].includes(s))setAuthOrigin('recibido');if(chatScreens.includes(s)&&['inicio','mensajes','mensajes-visitante'].includes(screen))setChatOrigin(screen);persist();setScreen(s);history.replaceState(null,'',href(s));setDraft('');setLocalMessages([]);};
 const back=()=>navigate(isChat?chatOrigin:screen==='legal'?legalOrigin:['registro','acceso'].includes(screen)?authOrigin:screen==='restricciones'?protectedOrigin:({registro:'recibido',acceso:'recibido',verificar:'registro',vinculando:'verificar',caducado:'recibido',recuperacion:'acceso',restricciones:'inicio',instalar:'inicio'})[screen]||'inicio');
 function user(text,time='10:17'){return <div className="bubble user"><div className="bubble-meta"><strong className="bubble-author">Tú</strong><span className="bubble-time">{time}</span></div><p>{text}</p><div className="bubble-delivery"><span className="delivery-ticks read" aria-label="Leído"><Icon name="check" size={13}/><Icon name="check" size={13}/></span></div></div>}
 function ia(text,children){return <div className="bubble assistant"><div className="lidia-message-heading"><span className="lidia-message-avatar" aria-hidden="true">L.</span><strong>LidIA · Asistente IA Gestadia</strong></div><p>{text}</p>{children}</div>}
 const button=(text,dest,style='primary')=><button className={`btn ${style}`} onClick={()=>navigate(dest)}>{text}</button>;
 function composerSend(){if(!draft.trim())return;const text=draft.trim();if(screen==='inicio')navigate('consulta');setLocalMessages(m=>[...m,text]);setDraft('');}
 function Chat(){return <section className="assistant-page assistant-chat-page"><div className="conversation">
 {screen==='consulta'&&<>{ia('¡Hola! Soy LidIA, tu asistente de Gestadia. Puedes consultar sobre tu canje sin crear una cuenta. ¿Qué necesitas saber?')}<p className="helper privacy-note">Tu consulta continúa en este chat. <button className="text-btn" onClick={()=>{setLegalOrigin(screen);navigate('legal')}}>Privacidad</button></p><div className="chips"><button onClick={()=>navigate('preguntas')}>Quiero canjear mi carnet</button></div></>}
 {screen==='preguntas'&&<>{user('Quiero canjear mi carnet.','10:17')}{ia('Vamos a comprobar los requisitos de tu permiso de conducir. ¿En qué país se expidió?')}<div className="chips">{['Perú','Colombia'].map(p=><button key={p} onClick={()=>{setPais(p);setCountryAnswered(true)}}>{p}</button>)}<button onClick={()=>navigate('revision')}>Otro país</button></div>{countryAnswered&&user(pais)}{ia('Después revisaremos la residencia, las fechas y los demás requisitos de tu caso.')}</>}
 {screen==='resultado'&&<>{user(pais,'10:19')}{ia('Hemos terminado las preguntas sobre los requisitos de tu canje.')}{user('Sí, resido en España.','10:21')}{ia('Con las respuestas de esta revisión podemos pasar tu caso a un gestor. ¿Quieres que te contacte?',<div className="stack">{button('Quiero que me contacte un gestor','contactar')}{button('Seguir consultando','preguntas','secondary')}</div>)}</>}
 {screen==='contactar'&&<>{user('Quiero que me contacte un gestor.','10:22')}{ia('Déjanos tu nombre y un teléfono o email para que el gestor pueda contactar contigo sobre tu canje.',button('Dejar mis datos','datos-contacto'))}<p className="helper privacy-note">Sólo se piden estos datos al solicitar el contacto del gestor.</p></>}
 {screen==='datos-contacto'&&<>{ia('¿Cómo prefieres que te contacte el gestor?')}<form className="card form-card" onSubmit={e=>{e.preventDefault();navigate('recibido')}}><h2>Datos para el gestor</h2><label>Nombre<input value={nombre} onChange={e=>setNombre(e.target.value)} required autoComplete="name"/></label><label>Contacto<select value={contactType} onChange={e=>{setContactType(e.target.value);setContacto(e.target.value==='email'?email:'+34 600 000 000')}}><option value="tel">Teléfono</option><option value="email">Email</option></select></label><label>{contactType==='email'?'Email':'Teléfono'}<input type={contactType} value={contacto} onChange={e=>{setContacto(e.target.value);if(contactType==='email')setEmail(e.target.value)}} required/></label><p className="helper">Usaremos estos datos para que un gestor de Gestadia te contacte sobre tu canje.</p><button className="btn primary" type="submit">Solicitar contacto del gestor</button><button className="text-btn" type="button" onClick={()=>navigate('preguntas')}>Seguir con mi consulta</button></form></>}
 {['recibido','cancelado'].includes(screen)&&<>{user('Quiero que me contacte un gestor.','10:22')}{ia('Hemos recibido tu solicitud. Un gestor de Gestadia contactará contigo por el teléfono o email que has indicado.',<div className="request-receipt"><strong>Solicitud recibida</strong><span>Contacto del gestor pendiente</span></div>)}{ia('Si quieres guardar esta conversación y recuperarla desde otros dispositivos, puedes crear tu cuenta o iniciar sesión.',<div className="stack">{button('Guardar en mi cuenta','registro')}{button('Ya tengo cuenta','acceso','secondary')}</div>)}<button className="text-btn defer" onClick={()=>navigate('cancelado')}>Seguir sin cuenta</button>{screen==='cancelado'&&ia('Puedes seguir hablando sin cuenta. Tu solicitud de contacto sigue recibida; no hace falta enviarla otra vez.')} {button('Ver mis conversaciones','mensajes-visitante','dark')}</>}
 {screen==='retomado'&&<>{user('Quiero canjear mi carnet.','10:17')}{ia('¿En qué país se expidió tu permiso de conducir?')}{user(pais,'10:19')}{user('Quiero que me contacte un gestor.','10:22')}{ia('Tu solicitud de contacto está recibida. El gestor te contactará por el medio indicado.')} {ia('Seguimos en la misma conversación. Ahora está guardada en tu cuenta para que puedas retomarla desde otros dispositivos.',<p className="linked-state"><Icon name="check" size={15}/>Conversación guardada en tu cuenta</p>)}{button('Ver mis conversaciones','mensajes','dark')}</>}
 {screen==='revision'&&<>{user('No lo tengo claro.','10:21')}{ia('Necesitamos revisar las respuestas que faltan antes de saber si podemos continuar con el canje. Puedes seguir consultando sin crear una cuenta ni dejar tus datos de contacto.')}<div className="stack">{button('Seguir revisando mi caso','preguntas','secondary')}{button('Ver servicios','servicios','dark')}</div></>}
 {localMessages.map((text,i)=><React.Fragment key={i}>{user(text,new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}))}</React.Fragment>)}
 </div></section>}
 function AccountForm(){return <section className="auth-page prototype-auth"><h1>{screen==='registro'?'Crea tu cuenta':'Iniciar sesión'}</h1><p className="muted">{authOrigin==='recibido'?'Guarda tu conversación y recupérala desde otros dispositivos. Tu solicitud al gestor ya está recibida.':'Accede a tus trámites y conversaciones con tu cuenta Gestadia.'}</p><form className="card form-card" onSubmit={e=>{e.preventDefault();navigate(authOrigin==='restricciones'?protectedOrigin:screen==='registro'?'verificar':'vinculando')}}><h2>{screen==='registro'?'Tu cuenta Gestadia':'Accede a tu cuenta'}</h2>{screen==='registro'&&<label>Nombre<input value={nombre} onChange={e=>setNombre(e.target.value)} required autoComplete="name"/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Contraseña<span className="password-field"><input type={visible?'text':'password'} placeholder="Tu contraseña" required minLength="8" autoComplete="off"/><button type="button" className="icon-btn password-toggle" aria-label={visible?'Ocultar contraseña':'Mostrar contraseña'} onClick={()=>setVisible(!visible)}><Icon name={visible?'eyeOff':'eye'}/></button></span></label>{screen==='registro'&&<p className="helper">Antes de crear tu cuenta, consulta los <button className="text-btn" type="button" onClick={()=>{setLegalOrigin(screen);navigate('legal')}}>Términos</button> y la <button className="text-btn" type="button" onClick={()=>{setLegalOrigin(screen);navigate('legal')}}>Privacidad</button>.</p>}<button className="btn primary" type="submit">{screen==='registro'?'Crear cuenta y continuar':'Entrar y continuar'}</button>{screen==='acceso'&&<button className="text-btn forgot" type="button" onClick={()=>navigate('recuperacion')}>¿Has olvidado tu contraseña?</button>}</form><div className="auth-switch">{screen==='registro'?'¿Ya tienes cuenta?':'¿Es tu primera vez?'} <button className="text-btn" onClick={()=>navigate(screen==='registro'?'acceso':'registro')}>{screen==='registro'?'Iniciar sesión':'Crear cuenta'}</button></div><button className="text-btn return-chat" onClick={()=>navigate(authOrigin==='recibido'?'cancelado':'restricciones')}>{authOrigin==='recibido'?'Volver a mi conversación':'Volver'}</button><div className="legal-links"><button className="text-btn" onClick={()=>{setLegalOrigin(screen);navigate('legal')}}>Privacidad</button><button className="text-btn" onClick={()=>{setLegalOrigin(screen);navigate('legal')}}>Términos</button><button className="text-btn" onClick={()=>{setLegalOrigin(screen);navigate('legal')}}>Soporte</button></div></section>}
 function Info(){const data={
 verificar:['Revisa tu email',`Te hemos enviado un enlace a ${email} para verificar tu cuenta. Tu conversación sigue guardada.`, 'Ya he verificado mi email','vinculando','shield'],
 vinculando:['Estamos recuperando tu conversación','Estamos vinculando tu cuenta con esta conversación. No abras un chat nuevo: tus mensajes y respuestas se conservan.','Comprobar de nuevo','retomado','message'],
 caducado:['Este enlace ha caducado','Tu conversación no se ha borrado. Vuelve a ella para pedir otro enlace y continuar el registro.','Volver a mi conversación','recibido','warning'],
 recuperacion:['Recupera tu acceso','Recupera la contraseña en el portal y vuelve aquí. Tu conversación seguirá esperando.','Volver a iniciar sesión','acceso','key'],
 restricciones:['Accede a tu cuenta','Puedes seguir hablando con LidIA sin cuenta. Los trámites y la atención de tu gestor necesitan acceso a tu cuenta.','Volver a LidIA','inicio','shield'],
 instalar:['Habla con LidIA en la APP','Si ya tienes la APP, abre tu consulta. Si la instalas ahora, vuelve a este enlace para entrar en la conversación.','Abrir Gestadia','consulta','spark'],
 legal:['Privacidad, términos y soporte','En el producto se mostrarán los documentos vigentes de Gestadia. Esta maqueta representa el retorno al recorrido sin enviar datos.','Volver',legalOrigin,'shield'],
 }[screen]; return <section className="workspace-page state-page"><div className={'state-icon '+(screen==='caducado'?'warning':'')}><Icon name={data[4]} size={28}/></div><h1>{data[0]}</h1><p className="muted">{data[1]}</p>{button(data[2],data[3])}{screen==='verificar'&&<><button className="text-btn" onClick={()=>setNotice('Ejemplo: se reenviaría el enlace al mismo email.')}>Reenviar email</button><button className="text-btn" onClick={()=>navigate('registro')}>Corregir mi email</button></>}{screen==='instalar'&&<><button className="btn secondary" onClick={()=>setNotice('En producción abrirá App Store. No se publica ni instala desde esta maqueta.')}>Descargar para iPhone</button><button className="btn secondary" onClick={()=>setNotice('En producción abrirá Google Play. No se publica ni instala desde esta maqueta.')}>Descargar para Android</button><p className="helper">Después de instalar, vuelve aquí y pulsa «Abrir Gestadia».</p></>}{screen==='vinculando'&&<p className="helper">Tu solicitud al gestor ya está recibida. Guardar el chat no la vuelve a enviar.</p>}{screen==='restricciones'&&<>{button('Iniciar sesión','acceso','secondary')}<p className="helper">Crear una cuenta gratuita no inicia un trámite ni contrata un servicio.</p></>}</section>}
 function Services(){return <section className="services-page"><p className="eyebrow">GESTIÓN 100% ONLINE</p><h1>Trámites y Gestiones DGT</h1><p className="muted">Servicio integral con tu gestor asignado y justificante provisional.</p><div className="service-benefits"><div><Icon name="check" size={18}/>Sin cita previa DGT</div><div><Icon name="check" size={18}/>Permiso provisional CSV</div></div><div className="stack">{['Canje de Carnet Extranjero','Transferencia de Vehículo','Duplicado de Carnet de Conducir'].map(t=><button className="card option" key={t} onClick={()=>setNotice('Servicio público accesible sin cuenta. Su formulario actual no cambia en esta propuesta.')}><span>{t}</span><Icon name="arrow" size={18}/></button>)}</div></section>}
 function Messages(){const visitante=screen==='mensajes-visitante';return <section className="workspace-page connected-messages"><div className="messages-title-row"><h1>Mensajes</h1><button className="messages-refresh" aria-label="Actualizar" onClick={()=>setNotice('Lista actualizada en la maqueta.')}><RefreshCw size={19} strokeWidth={1.8}/></button></div><p className="muted">Tus conversaciones con LidIA.</p><label className="conversation-search"><Search size={19} strokeWidth={1.8}/><span className="sr-only">Buscar conversaciones</span><input type="search" placeholder="Buscar conversaciones" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="new-conversation-links"><a href={href('consulta')} onClick={e=>{e.preventDefault();navigate('consulta')}}> <Icon name="spark" size={18}/>Nueva conversación</a><a href={href('restricciones')} onClick={e=>{e.preventDefault();navigate('restricciones')}}><Icon name="user" size={18}/>Atención Gestadia</a></div><div className="conversation-list-heading"><h2>Tus conversaciones</h2><span>1 conversación</span></div>{title.toLowerCase().includes(search.toLowerCase())?<article className="conversation-card"><div className="conversation-row"><button className="conversation-link" onClick={()=>navigate(visitante?'recibido':'retomado')}><span className="conversation-avatar assistant"><Icon name="spark" size={18}/></span><div className="conversation-details"><strong>{title}</strong><div className="conversation-info"><span className="conversation-interlocutor">LidIA</span><span className="conversation-status">Abierta</span></div><p className="conversation-preview">Tu conversación y respuestas están guardadas.</p><dl className="conversation-dates"><div><dt>Creada</dt><dd>10 oct 2026, 10:17</dd></div><div><dt>Último mensaje</dt><dd>10 oct 2026, {visitante?'10:22':'10:26'}</dd></div></dl></div><Icon name="arrow" size={15}/></button><button className="conversation-rename-trigger" aria-label="Renombrar conversación" onClick={()=>setRenaming(!renaming)}><Pencil size={18} strokeWidth={1.8}/></button></div>{renaming&&<form className="conversation-rename" onSubmit={e=>{e.preventDefault();setRenaming(false)}}><label>Nombre de la conversación<input value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="conversation-rename-actions"><button className="btn dark">Guardar</button><button className="text-btn" type="button" onClick={()=>setRenaming(false)}>Cancelar</button></div></form>}</article>:<p className="helper">No hay conversaciones con ese nombre.</p>}<p className="helper list-scope">{visitante?'Estas conversaciones están guardadas en esta instalación. Crea tu cuenta para recuperarlas en otros dispositivos.':'Esta conversación está guardada en tu cuenta. Puedes retomarla cuando quieras.'}</p></section>}
 return <>{!captura&&<aside className="review-mode">Maqueta · Sin conexión a LidIA <a href="./index.html#pantallas">Ver el flujo</a>{screen==='preguntas'&&<button onClick={()=>navigate('resultado')}>Ver ejemplo de resultado</button>}</aside>}<div className={"app-shell "+(!captura?"with-review-mode":"")}>
 <header className={isChat?'manager-chat-header':'app-header'}>{!['inicio','mensajes','mensajes-visitante','servicios'].includes(screen)&&<button className="icon-btn" aria-label="Volver" onClick={back}><Icon name="back"/></button>}{isChat?<><h1>Habla con LidIA</h1><button className="icon-btn" aria-label="Contactar con un gestor" onClick={()=>navigate(['consulta','preguntas','revision'].includes(screen)?'revision':['recibido','cancelado','retomado'].includes(screen)?screen:'contactar')}><Icon name="phone" size={18}/></button></>:<><a href={href('inicio')} className="brand" aria-label="Gestadia, inicio"><span>gestadia<b>.</b></span><small>Trámites DGT Online</small></a>{!auth&&<div className="header-actions"><button className="icon-btn" aria-label="Notificaciones" onClick={()=>setNotice('No tienes notificaciones pendientes.')}><Icon name="bell"/></button><button className="icon-btn" aria-label="Mi cuenta" onClick={()=>navigate('acceso')}><Icon name="user"/></button></div>}</>}</header>
 <main className="app-main" id="main">{isChat?<Chat/>:screen==='inicio'?<section className="assistant-page"><h1>¿Qué trámite de Tráfico necesitas gestionar hoy?</h1><p className="muted">Consulta a LidIA sobre tu canje. Empieza sin cuenta y sin dejar tus datos de contacto.</p><div className="stack"><button className="card option" onClick={()=>navigate('consulta')}><span>Quiero canjear mi carnet de conducir extranjero</span><span className="probe-chevron">›</span></button><button className="card option" onClick={()=>navigate('servicios')}><span>Cómo transferir un coche y cambiar titular</span><span className="probe-chevron">›</span></button><button className="card option" onClick={()=>navigate('servicios')}><span>He perdido el carnet y necesito un duplicado urgente</span><span className="probe-chevron">›</span></button></div><a className="home-resume-chat" href={href('recibido')}>Continuar mi conversación</a><p className="helper privacy-note">Primero comprobamos los requisitos de tu canje. <button className="text-btn" onClick={()=>{setLegalOrigin(screen);navigate('legal')}}>Privacidad</button></p></section>:['registro','acceso'].includes(screen)?<AccountForm/>:['mensajes','mensajes-visitante'].includes(screen)?<Messages/>:screen==='servicios'?<Services/>:<Info/>}</main>
 {!auth&&screen!=='instalar'&&<footer className="app-footer">{(isChat||screen==='inicio')&&<div className="footer-actions">{screen==='inicio'&&<button className="contact-cta" onClick={()=>navigate('restricciones')}>Hablar con un gestor</button>}<div className="footer-lidia-composer"><form className="composer" onSubmit={e=>{e.preventDefault();composerSend()}}><textarea rows="1" placeholder="¿Qué necesitas?" aria-label="Tu consulta" value={draft} onChange={e=>setDraft(e.target.value)}/><button type="button" className="icon-btn" aria-label="Dictar consulta" onClick={()=>setNotice('El dictado no se activa en esta maqueta. Puedes escribir.') }><Icon name="mic" size={20}/></button><button type="submit" className="send-btn" aria-label="Enviar consulta"><Icon name="send" size={19}/></button></form></div></div>}<div className="dock-zone"><nav className="dock" aria-label="Navegación principal">{[['inicio','LidIA','spark'],['restricciones','Trámites','clipboard'],[['retomado','mensajes'].includes(screen)?'mensajes':'mensajes-visitante','Mensajes','message'],['servicios','Servicios','bag']].map(([s,t,i])=><a className={(t==='LidIA'&&(isChat||screen==='inicio')||['mensajes','mensajes-visitante'].includes(screen)&&t==='Mensajes'||screen==='servicios'&&t==='Servicios'||screen==='restricciones'&&t==='Trámites')?'active':''} key={t} href={href(s)} onClick={e=>{e.preventDefault();navigate(s)}}><Icon name={i} size={21}/><span>{t}</span></a>)}</nav></div></footer>}
 {notice&&<div className="warning-toast" role="status"><Icon name="warning"/><p>{notice}</p><button className="icon-btn" aria-label="Cerrar aviso" onClick={()=>setNotice('')}><Icon name="close" size={18}/></button></div>}
 </div></>
}
const root=createRoot(document.getElementById('root'));
root.render(<App/>);
if(import.meta.hot)import.meta.hot.dispose(()=>root.unmount());
